- name: Configurar balanceador NGINX
  hosts: balanceadores
  become: yes
  tasks:
    - name: Instalar NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copiar archivo de configuración
      copy:
        src: ../../nginx/load-balancer.conf
        dest: /etc/nginx/nginx.conf
        backup: yes

    - name: Reiniciar servicio NGINX
      service:
        name: nginx
        state: restarted
