global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['pg_master:9187', 'pg_replica:9187']
